### ISSUE TITLE
Add to docs, that you have to import snipcart

### ISSUE THREAD

**Issue by baermathias** [nuxt-modules/snipcart#47]
Inside nuxt.config.ts you have to add an import 
`import '@nuxtjs/snipcart'`
Else you get an error if adding the `snipcart` property to nuxt.config.ts, at least this was for me the case:
`Argument of type ... is not assignable to parameter of type 'NuxtConfig'.`

**Comment by flozero** [comment]
hey @baermathias thanks for the issue. Can you explain what do you mean exactly and what is the project you try to add it ? And which nuxt version also ? Typescript or not ?
The playground doesn't import directly snipcart and just use the modules

**Comment by baermathias** [comment]
The issue is gone for some reason, so I am closing this.
